@startuml
left to right direction

node "Разработка мобильного приложения «ЭкоКарта»" as root

package "Мобильное приложение" as mobile {

package "Модуль карт" {
    node "Реализовать интеграцию с Яндекс Картами" as map_sdk
    node "Реализовать отображение маркеров" as map_markers
    node "Реализовать фильтры" as map_filters
    node "Реализовать геолокацию" as map_geolocation
    node "Реализовать построение маршрутов" as map_routes
}

package "Модуль карточек пунктов" {
    node "Реализовать отображение карточек пунктов" as points_cards
}

package "Личный кабинет" {
    node "Реализовать регистрацию" as registration
    node "Реализовать авторизацию" as authorization
    node "Реализовать историю сдач" as history
}

package "Система уведомлений" {
    node "Реализовать обработчик push-уведомлений" as push_client
    node "Реализовать настройку уведомлений" as push_settings
}

}

root -- mobile

package "Бэкенд" as server_app {
    package "База данных" {
        node "Спроектировать схему БД" as db_scheme
    }
    package "API" {
        node "Реализовать API точек и фильтров" as api_points
        node "Реализовать API профиля и истории" as api_profile
    }
    package "Система уведомлений" {
        node "Реализовать сервис push-уведомлений" as api_push
    }
    package "Админ-панель" {
        node "Реализовать админ-панель управления" as admin_panel
    }
}

root -- server_app

package "Дизайн и UX" as design {
    node "Разработать User Flow и Wireframes" as ux_flow
    node "Разработать UI Kit и компоненты" as ui_kit
    node "Нарисовать иконки" as graphics
}

root -- design

package "Маркетинг и контент" as marketing {
    node "Написать тексты карточек" as content_texts
    node "Написать сценарии акций и пушей" as promo_content
    node "Разработать материалы для сторов" as aso
}

root -- marketing

package "Инфраструктура и деплой" as infrastructure {
    node "Настроить сервер" as hosting
    node "Выполнить релиз в сторы" as release
}

root -- infrastructure

@enduml